# https://github.com/golangci/golangci-lint/blob/master/.golangci.yml
linters:
  enable-all: true
  disable:
    - exportloopref
    - testifylint
    - paralleltest
    - exhaustruct
    - depguard
    - nonamedreturns
    - ireturn
    - gochecknoglobals
    - tagalign
    - revive
    - nolintlint
    - gci
    - gofumpt
    - goimports
    - gofmt

linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-names:
      - r
      - w
  dupl:
    threshold: 100
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 60
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 15
  godox:
    keywords:
      - FIXME
      - TODO
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  mnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
    ignored-functions:
      - strings.SplitN
  govet:
    enable:
      - nilness
      - shadow
  errorlint:
    asserts: false
  lll:
    line-length: 122
  misspell:
    locale: US
    ignore-words:
      - "importas" # linter name
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  revive:
    rules:
      - name: indent-error-flow
      - name: unexported-return
        disabled: true
      - name: unused-parameter
      - name: unused-receiver
  wrapcheck:
    ignoreSigs:
      - status.Error(
      - fmt.Errorf(


run:
  timeout: 5m
  go: 1.23.3